#MHDBLACKWOLF
#PKG INSTALL
import os

print("""========================================""")
print("[+] everything successfully installed :)")
print("[+] Happy installed <3")
print("========================================")
os.system("pkg update && upgrade")
os.system("pkg install git -y ")
os.system("pkg install python -y")
os.system("pkg install python2 -y")
os.system("pkg install unzip -y")
os.system("pkg install nano -y")
os.system("pkg install cat -y")
os.system("pkg install curl -y")
os.system("pkg install wget -y")
os.system("pkg install w3m -y")
os.system("pkg install php -y ")
os.system("pkg install nodejs -y")
os.system("apt install golang -y")
os.system("apt install host -y")
os.system("apt install havij -y")
os.system("pkg install figlet -y")
os.system("pkg install wget -y")
os.system("pkg install cfengine -y")
os.system("pkg install db -y")
os.system("pkg install netpb -y")
os.system("pkg install postgresql -y")
os.system("pkg install uftrace -y")
os.system("pkg install python -y")
os.system("pkg install python2 -y")
os.system("pkg install python3 -y")
os.system("pkg install java -y")
os.system("pkg install fish -y")
os.system("pkg install ruby -y")
os.system("pip install --upgrade pip")
os.system("pkg install host -y")
os.system("pkg install php -y")
os.system("pkg install perl -y")
os.system("pkg install nmap -y")
os.system("pkg install bash -y")
os.system("pkg install clang -y")
os.system("pkg install w3m -y")
os.system("pkg install havij -y")
os.system("pip install --upgrade pip")
os.system("pkg install figlet -y")
os.system("pkg install cowsay -y")
os.system("pkg install curl -y")
os.system("pkg install tar -y")
os.system("pkg install zip -y")
os.system("pip2 install requests bs4")
os.system("pkg install unzip -y")
os.system("pip install --upgrade pip")
os.system("pkg install tor -y")
os.system("pkg install google -y")
os.system("pkg install sudo -y")
os.system("pkg install wget -y")
os.system("pkg install wireshark -y")
os.system("pkg install wgetrc -y")
os.system("pkg install wcalc -y")
os.system("pkg install wcalc -y")
os.system("pkg install bs4 -y")
os.system("pkg install bmon -y")
os.system("pkg install unrar -y")
os.system("pkg install toilet -y")
os.system("pkg install proot -y")
os.system("pkg install net-tools -y")
os.system("pkg install golang -y")
os.system("pip install chroot -y")
os.system("pkg install openssl -y")
os.system("pkg install cmatrix -y")
os.system("pkg install openssh")
os.system("pip install --upgrade pip")
os.system("pkg install macchanger ")
os.system("pip install colorama ")
os.system("pip2 install mechanize ")
os.system("pip2 install requests ")
os.system("pip install --upgrade pip")
os.system("pkg install root-repo -y")
os.system("pkg install unstable-repo -y")
os.system("pkg install x11-repo -y")
os.system("apt update && apt upgrade -y")
os.system('clear')
os.system('nano .termux/termux.properties')
print("[['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]")
print("========================================")
print("[+] everything successfully installed :)")
print("[+] Happy Hacking <3")
print("========================================")
